### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by sathishbabu96** [pylover/pyvalidate#2]
Hello, I am getting an error when I try to use pyvalidate.

```
Traceback (most recent call last):
  File "/home/test/.PyCharmCE2018.2/config/scratches/scratch.py", line 1, in <module>
    from pyvalidate import validate, ValidationException
  File "/home/test/PycharmProjects/CherrypySecurity/venv/lib/python3.5/site-packages/pyvalidate/__init__.py", line 4, in <module>
    from pyvalidate import ArgumentTypeException,DenialException,MandatoryException,ParameterTypeException,ParameterValueException,validate,validate_parameters,ValidationException
ImportError: cannot import name 'ArgumentTypeException'
```

**Comment by pylover** [comment]
Hi, this project is just compatible with Python2.7 and it's not maintained anymore.

Sorry, bro. 

But you can find some useful validation mechanisms by checking the nanohttp validation module: https://github.com/Carrene/nanohttp/blob/master/nanohttp/validation.py

Please feel free to ask whatever about it.

**Comment by sathishbabu96** [comment]
It's okay. I wrote my own validator for my use case
